name: GitHub - Activity - Readme

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: GitHub - Activity - Readme
        uses: jamesgeorge007/github-activity-readme@v0.3.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: "chore(readme): update with the recent activity"
          MAX_LINES: 10
