name: GitHub - Activity - Readme

on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: GitHub - Activity - Readme
        uses: jamesgeorge007/github-activity-readme@v0.3.6
        env:
          COMMIT_MSG: "chore(readme): update with the recent activity"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAX_LINES: 10
